### ISSUE TITLE
Forgot backslash before Auth call

### ISSUE THREAD

**Issue by joaoeduardo** [stevebauman/inventory#1]
In the line 26 of the UserIdentificationTrait.php file is missing a backslash before Auth::user()->getAuthIdentifier();.

**Comment by stevebauman** [comment]
Thanks! Will be fixed shortly. Haven't been able to test larvels stock auth yet since I use sentry.

**Comment by stevebauman** [comment]
Ok fixed dce1251fedbf555d607c9669672295ad31ec9214

**Comment by joaoeduardo** [comment]
Thank you!

**Comment by stevebauman** [comment]
No problem! More updates coming shortly, including pre-made models for users who don't need / want their own models defined
