### ISSUE TITLE
Add optional 'reason' parameter to InventoryTransaction action methods

### ISSUE THREAD

**Issue by rawcreative** [stevebauman/inventory#15]
Something I noticed today when doing some testing that that any stock movements that were the result of a transaction have just the default reason populated. It would be great if a 'reason' could be passed to the action methods on the transaction e.g. reserved($qty, 'My Reason), which would get passed to the corresponding stock method so it gets recorded in the movements table. Or at the very least, pass the transaction name or ID to the stock method when it's called so there is some link between transactions and movements (other than additional complex queries).

Thoughts?

**Comment by stevebauman** [comment]
Yea I definitely agree with this. Completely slipped my mind. I'll have this implemented tonight or tomorrow :), thanks!

**Comment by stevebauman** [comment]
Just an update, was almost done including reasons & cost into transactions, but the trait is getting huge now. I've decided to do a complete refactor on the `InventoryTransactionTrait` as well as include this update in it. This will take another day or so. Nothing will be changed API wise (all functions will remain), just need to organize this code better.

**Comment by rawcreative** [comment]
I was planning on submitting a PR for it but since you’re refactoring anyway, the boot() method in the traits should be changed to bootTraitName to use Eloquent’s trait auto-booting functionality to avoid conflicts/breakage in the model if someone needs to implement a boot method in the model.(I’ve ran into this twice already).

**Comment by stevebauman** [comment]
Nice catch! I've never ran into this before so I appreciate you letting me know. I also didn't know that eloquent has an auto-booting functionality. This will all be fixed in the next update.

**Comment by stevebauman** [comment]
Ok boot methods are fixed in [v1.4.4](https://github.com/stevebauman/inventory/releases/tag/v1.4.4), working on transaction refactoring now.

**Comment by stevebauman** [comment]
Refactoring is done, going to finish adding reason and cost to transactions tonight!

**Comment by stevebauman** [comment]
Finished [v1.5.0](https://github.com/stevebauman/inventory/releases/tag/v1.5.0)
