### ISSUE TITLE
track each item separately

### ISSUE THREAD

**Issue by apropos** [stevebauman/inventory#19]
How do I go about tracking every single piece of item that has unique barcode attached?  I've tried setting up the code and did the example in usage document but it seems like this code tracks the quantity of item as a whole for each location.  Is it possible to use this code to track movement of each piece of item through the different locations?

**Comment by stevebauman** [comment]
Unfortunately this functionality doesn't exist right now in this package, however I've been thinking about adding this in. I haven't spent too much time thinking on the implementation but if you have some ideas then definitely throw some my way! I'll always be looking to improve this package.

**Comment by apropos** [comment]
I'll try to go over the code in more detail and see what I can help with.

**Comment by stevebauman** [comment]
Ok great. What'd I'd need help with mostly is the database schema. Something that ties in the existing inventory table to the new 'individual quantity' table. Once the migration is in place, I can work with coding the API.

I'll be doing some research tonight and onward to see how other inventory systems manage this.
