### ISSUE TITLE
Implementing Prices / Costs

### ISSUE THREAD

**Issue by stevebauman** [stevebauman/inventory#24]
New feature to be implemented. Prices and costs per item can be managed. This will allow devs to add currencies (ex. USD, CAD, Euros) and have separate costs/currencies per item.

**Comment by brunogaspar** [comment]
Seems a nice addition :+1: 

I'm doing something similar, but i don't take into consideration the currency, since we only store the prices in euros, but whenever we change an item price and someone has that item in their cart, we show a notification, similar to how Amazon does it.

**Comment by stevebauman** [comment]
Thanks! That's very cool and a great idea. I'll have to build in events when prices have changed so devs can listen for them and be able to build their own solution around it.

**Comment by cdarken** [comment]
Hi, @stevebauman. Is this implemented? Or it's still work in progress? I need to add prices for an inventory item, is there a workaround? I didn't find something in the docs.

**Comment by donnigunawan** [comment]
Guys, you're talking about prices and cost of each item. Which one are you going to consider as an item? is that the "Inventory" or "Variant"? are you going to put the cost in one of their table? Thank you

**Comment by donnigunawan** [comment]
I am sorry, I wasn't see clearly that the Variant is actually the Inventory too
