### ISSUE TITLE
Database Migration Issue

### ISSUE THREAD

**Issue by donnigunawan** [stevebauman/inventory#27]
Hi, All set for Laravel 4.2 but when I try to migrate I found this error : 
 
Migration table created successfully.

  [Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1005 Can't create table 'db_laravel_invento
  ry.#sql-ad0_237' (errno: 150) (SQL: alter table `metrics` add constraint me
  trics_user_id_foreign foreign key (`user_id`) references `users` (`id`) on
  delete set null on update restrict)

  [PDOException]
  SQLSTATE[HY000]: General error: 1005 Can't create table 'db_laravel_invento
  ry.#sql-ad0_237' (errno: 150)

migrate [--bench[="..."]] [--database[="..."]] [--force] [--path[="..."]] [--pac
kage[="..."]] [--pretend] [--seed]

If any way to solve this issue? Thank you

**Comment by stevebauman** [comment]
Hi, you need a `users` database table to be able to run the inventory migrations. This is why Laravel's Auth, Sentinel or Sentry is required as they create this table during installation. Run the command `php artisan inventory:check-schema` to view which tables are required.

**Comment by stevebauman** [comment]
Also, if you have a `users` database table, but it is not named `users`, then you must publish the inventory migrations and modify the foreign keys on the tables that require a user ID foreign key.

**Comment by donnigunawan** [comment]
thank you mr steve..

**Comment by stevebauman** [comment]
No problem! Please let me know if you encounter any other issues. Thanks!

**Comment by stilllifee** [comment]
Hi, All set for Laravel 5.2 but when I try to migrate I found this error :
$ php artisan migrate

←[37;41m
       ←[39;49m
←[37;41m  [Illuminate\Database\QueryException]
       ←[39;49m
←[37;41m  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'metrics' already exists (SQL: create table `metrics` (`id` int unsigned not null auto_increment pri
mary   ←[39;49m
←[37;41m  key, `created_at` timestamp null, `updated_at` timestamp null, `user_id` int unsigned null, `name` varchar(255) not null, `symbol` varchar(255) not null) default c
harac  ←[39;49m
←[37;41m  ter set utf8 collate utf8_unicode_ci)
       ←[39;49m
←[37;41m
       ←[39;49m

←[37;41m                                                                                           ←[39;49m
←[37;41m  [PDOException]                                                                           ←[39;49m
←[37;41m  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'metrics' already exists  ←[39;49m
←[37;41m

**Comment by stilllifee** [comment]
Laravel 5.2, I found this error:

$ php artisan inventory:install

←[32mChecking Database Schema←[39m
←[32mSchema dependencies are all good!←[39m

←[37;41m                                                                                                       ←[39;49m
←[37;41m  [Stevebauman\Inventory\Exceptions\Commands\DatabaseTableReservedException]                           ←[39;49m
←[37;41m  Table: metrics already exists. This table is reserved. Please remove the database table to continue  ←[39;49m
←[37;41m
