### ISSUE TITLE
Vendor publish Can't locate path

### ISSUE THREAD

**Issue by mberizzo** [stevebauman/inventory#28]
Hi! I have an error when execute "php artisan vendor:publish"

The error is "Can't locate path: </mifolder/vendor/stevebauman/inventory/src/Stevebauman/Inventory../../../config/config.php>
"

**Comment by stevebauman** [comment]
Hi, are you sure this is an Inventory issue? Have you recently installed other packages? Unfortunately the error you describe could happen with any Laravel package.

**Comment by mberizzo** [comment]
Hi! It is rare. I had to manually copy files, for solve the problem.

I do not remember that I have gone through another package

**Comment by stevebauman** [comment]
Hmm I just tested on a clean Laravel 5.1 install and it worked as expected. Unfortunately there isn't much I can go on with the information you've provided.

**Comment by sihendra** [comment]
Hi Steve, 

Its kinda weird, I am experiencing the same problem with clean install of Laravel 5.1 and Inventory 1.7.3. Here is the error shown:
```
#php artisan vendor:publish
Can't locate path: </var/www/myapp/vendor/stevebauman/inventory/src/Stevebauman/Inventory../../../config/config.php>
Can't locate path: </var/www/myapp/vendor/stevebauman/inventory/src/Stevebauman/Inventory../../../migrations/>
Publishing Complete!
```
I fixed it by removing excessive '..' in the config and migrations path in the InventoryServiceProvider class. The valid paths are:
- /var/www/myapp/vendor/stevebauman/inventory/src/Stevebauman/Inventory/../../migrations/
- /var/www/myapp/vendor/stevebauman/inventory/src/Stevebauman/Inventory/../../configs/config.php

**Comment by stevebauman** [comment]
Hi @sihendra, this is definitely odd. This may be an issue of me working on windows and you're both on linux. I'm going to troubleshoot further, thanks for the information!

**Comment by stevebauman** [comment]
@sihendra, Can you try installing `v1.7.4`? Folder structure has been reverted for PSR-4 compatibility. This should fix your issues for publishing the configurations on linux.

**Comment by sihendra** [comment]
@stevebauman I have installed v1.7.4 and v1.7.5 and vendor:publish worked fine on both versions. 
Thanks.

Btw there was one thing, running 'artisan migrate' failed on Laravel 5.1 clean install. 
To get it working, I renamed date part in *_create_users_table.php to older than *_create_metrics_table.php

**Comment by stevebauman** [comment]
Great to hear!

> Btw there was one thing, running 'artisan migrate' failed on Laravel 5.1 clean install. 
To get it working, I renamed date part in *_create_users_table.php to older than *_create_metrics_table.php

This is expected because the migrations for Laravel 5.1 have an updated timestamp which is later than Inventory's migrations. The requirements state that you must have a `users` table (or similar) before running the inventory migrations.

**Comment by dinesh829269** [comment]
i resolved the issue by downloading the latest version.
In your composer replace 
"stevebauman/inventory" : "1.6.*"
with 
"stevebauman/inventory" : "dev-master"

and composer update.

**Comment by Aronovartur** [comment]
used "stevebauman/inventory" : "dev-master" 

gave new error: 

[ReflectionException]
  Class translator does not exist

**Comment by pablorq** [comment]
Hi!

Where at 'composer.json' do I have to add "stevebauman/inventory" : "1.6.*" ?

Regards

**Comment by chagell** [comment]
> Hi!
> 
> Where at 'composer.json' do I have to add "stevebauman/inventory" : "1.6.*" ?
> 
> Regards

Just change in the composer.json this one "stevebauman/inventory" : "1.6.*" to "stevebauman/inventory" : "1.7.*" and it will work fine
