### ISSUE TITLE
1.8 release date

### ISSUE THREAD

**Issue by asaf050** [stevebauman/inventory#29]
Hey,
There is any release date for 1.8?
I really wait for the  kits/bundle feature.

Thanks

**Comment by stevebauman** [comment]
Hi @asaf050, thanks for the question. It's coming, but unfortunately I can't give a release date at the current time. I'm working on several other projects right now single handedly. 

However I can say it will *most likely* be released within the coming month(s).

**Comment by asaf050** [comment]
Hey @stevebauman,
Are you looking for a job?

**Comment by stevebauman** [comment]
Hi @asaf050, please email me at steven_bauman@outlook.com.

**Comment by natsu90** [comment]
I'm also looking forward to 1.8 release for Inventory Kit feature. Hope can have this very soon.

**Comment by eugenevdm** [comment]
Personally I'm really struggling to see the difference between an Inventory Kit and an Assembly. Maybe the terms are throwing me off. Can someone explain in baby terms what the difference is?

**Comment by rawcreative** [comment]
In general, raw materials are comprised to make a finished product or 'Assembly', where multiple inventory items are consolidated to make a new, single item with it's own inventory counts, sku, etc. Kits or Bundles on the other hand are typically inventory items or finished products that are just grouped and sold together as a package, but can still be sold individually.

As an example, a computer would be considered an assembly. Typically you can buy just the computer OR for a slightly higher price, you can buy a 'kit' containing the computer, monitor, keyboard, etc.

**Comment by donnigunawan** [comment]
I wish you have time to release the 1.8 :)
