### ISSUE TITLE
Localization in config files

### ISSUE THREAD

**Issue by rawcreative** [stevebauman/inventory#3]
In L5, currently an exception is thrown when attempting to use localization in the config files. The exception is thrown by the container and relates to the Log class, and based on some quick testing I don't think this is an issue with the package but with laravel itself. I've filed an issue on the framework repo https://github.com/laravel/framework/issues/7467 to see if this is a bug or expected behavior when using localization in the config files.

**Comment by stevebauman** [comment]
Nice catch, if this is ends up being an issue with laravel 5 I'll most likely just move the translations out of the configuration file, thanks!

**Comment by rawcreative** [comment]
Looks like that's the case, it's apparently too early in the request lifecycle to use localization in the config files.

**Comment by stevebauman** [comment]
Ok, thanks for the update on this, I'll remove the trans functions from the configuration file
