### ISSUE TITLE
 Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by JogoTopMideSup** [stevebauman/inventory#30]
hello, im historian student and made with a friend a inventory (in paper and pencil, and now excel) of archaeological artifacts. When more youth i get some contact with php so, im here trying to run your Laravel app for the first time to later do a mysql db. 

When i access the public folder through the browser i got:
 Whoops, looks like something went wrong.

(i used find in the files but.... got 21 matches.)

I installed without errors.

**Comment by JogoTopMideSup** [comment]
Ok, I need a Exception Handler like Bugsnag. Other free alternative?

**Comment by stevebauman** [comment]
Hi @JogoTopMideSup,

Inventory isn't a fully built application for use. Inventory is a *package* meant for creating **your own** web application for Inventory Management. This merely provides you the tools to help you accomplish this.

You should learn more about Laravel and PHP in general before diving into Inventory. If you run into any troubles using Inventory itself, then definitely let me know, thanks!
