### ISSUE TITLE
Problem with artsian publish

### ISSUE THREAD

**Issue by asaf050** [stevebauman/inventory#31]
Hey,
I try to install the package but i'm getting the following error:
`Can't locate path: </var/www/laravel/vendor/stevebauman/inventory/src/Stevebauman/Inventory../../../config/config.php>
Can't locate path: </var/www/laravel/vendor/stevebauman/inventory/src/Stevebauman/Inventory../../../migrations/>`

Any idea? (Laravel 5)

**Comment by stevebauman** [comment]
Hi, this is a known issue with Linux, please run `composer update` and try again. Let me know your result!

**Comment by asaf050** [comment]
Hey,
Thanks for the fast reply!
I've tried composer update & sudo composer update but I get the same errors.

**Comment by stevebauman** [comment]
Hmm judging by the path it's trying to locate, it looks like your not on `v1.7.4` or higher. This was fixed in that update. I'm assuming you're trying to publish the configuration & migrations?

**Comment by asaf050** [comment]
Yes, I was on 1.6.*, updating the composer to 1.7.5 solve the problem.

Thanks!

**Comment by stevebauman** [comment]
No problem!
