### ISSUE TITLE
F&B inventory implementation

### ISSUE THREAD

**Issue by natsu90** [stevebauman/inventory#37]
I've got `MenuItem` model in my F&B app and I want to implement inventory feature, how do I do this?

**Comment by stevebauman** [comment]
I'm not sure I understand. Inventory only *helps* you build an inventory solution. It's not a fully built application. If you're looking to implement Inventory, there's plenty of documentation to help you do so.

**Comment by natsu90** [comment]
I understand it's not a fully built app. I already have an app, and I want to implement Inventory. I did follow the installation documentation, but not sure how to implement with existing product item model. I have `MenuItem` model as the product table, and I'll do as below, is it correct? 

````
// MenuItem.php
....
public function inventory()
{
    return $this->hasOne('Inventory', 'inventory_id');
}
....
````
````
// Inventory.php
....
public function menuItem()
{
    return $this->belongsTo('MenuItem', 'menu_item_id');
}
....
````

**Comment by stevebauman** [comment]
Apologies for the long response on this. Yup that's definitely an option if you're looking to bind a single inventory product to a menu item.

**Comment by stevebauman** [comment]
So for example in your case, it would look something like:

```php
$menuItem = MenuItem::find(1);

$location = Location::find(1);

$menuItem->inventory->addToLocation(50, $location);
```
