### ISSUE TITLE
Unable to install completely

### ISSUE THREAD

**Issue by blackyzero** [stevebauman/inventory#45]
Hi,

I tried to install but got following error with composer update command:

 - Installing hamcrest/hamcrest-php (v1.2.2)
    Downloading: 100%         

  - Installing mockery/mockery (0.9.4)
    Downloading: 100%         

illuminate/support suggests installing jeremeamia/superclosure (Required to be able to serialize closures (~2.2).)
illuminate/support suggests installing paragonie/random_compat (Provides a compatible interface like PHP7's random_bytes() in PHP 5 projects (~1.1).)
illuminate/support suggests installing symfony/polyfill-php56 (Required to use the hash_equals function on PHP 5.5 (~1.0).)
illuminate/support suggests installing symfony/process (Required to use the composer class (2.8.*|3.0.*).)
illuminate/support suggests installing symfony/var-dumper (Improves the dd function (2.8.*|3.0.*).)
illuminate/filesystem suggests installing league/flysystem (Required to use the Flysystem local and FTP drivers (~1.0).)
illuminate/filesystem suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
illuminate/filesystem suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
symfony/translation suggests installing symfony/config ()
symfony/translation suggests installing psr/log (To use logging capability in translator)
illuminate/database suggests installing doctrine/dbal (Required to rename columns and drop SQLite columns (~2.4).)
illuminate/database suggests installing fzaninotto/faker (Required to use the eloquent factory builder (~1.4).)
illuminate/database suggests installing illuminate/pagination (Required to paginate the result set (5.2.*).)
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/process ()
symfony/console suggests installing psr/log (For using the console logger)
illuminate/console suggests installing guzzlehttp/guzzle (Required to use the ping methods on schedules (~5.3|~6.0).)
illuminate/console suggests installing mtdowling/cron-expression (Required to use scheduling component (~1.0).)
illuminate/console suggests installing symfony/process (Required to use scheduling component (2.8.*|3.0.*).)
sebastian/global-state suggests installing ext-uopz (*)
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Writing lock file
Generating autoload files
# 

Please show me how to fix it.
Thank you.

**Comment by stevebauman** [comment]
I don't see the issue here? Composer is just suggesting installing different packages?

These aren't errors.

**Comment by blackyzero** [comment]
Hi Steve,

Thanks for your respond.

I have tried to install these requirements, but got following message at the end:
PHP Warning:  Module 'mysql' already loaded in Unknown on line 0
PHP Warning:  Module 'mysql' already loaded in Unknown on line 0
PHP Warning:  Module 'openssl' already loaded in Unknown on line 0
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package dflydev/markdown is abandoned, you should avoid using it. Use michelf/php-markdown instead.
Generating autoload files

Then, i ran, composer update, but got following message:
# composer update
PHP Warning:  Module 'mysql' already loaded in Unknown on line 0
PHP Warning:  Module 'mysql' already loaded in Unknown on line 0
PHP Warning:  Module 'openssl' already loaded in Unknown on line 0
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package dflydev/markdown is abandoned, you should avoid using it. Use michelf/php-markdown instead.
Generating autoload files

Please advise how to fix the issue.

By the way, Is there any alternative to clone the latest working project? :)

Thank you.
