### ISSUE TITLE
Kits & Assemblies

### ISSUE THREAD

**Issue by rawcreative** [stevebauman/inventory#6]
I'm not sure if this is on your roadmap or not, but it would be great if this package supported kitting/bundling or assemblies. I'm currently using this in an app for a company who assembles all of their end products from raw materials and needs to track both materials and assembled goods. I'm currently using a closure table to handle the assemblies and it seems to be working out ok so far. If this is something you want to/plan on adding, I'd be happy to extract out the relevant code once this project wraps up and send a PR if you'd like (or assist with another implementation).

**Comment by stevebauman** [comment]
I'm always up for adding new features, though I'd definitely like to see how you've implemented it to get started on it. I've never worked with kitting or assemblies unfortunately. Is an inventory assembly just a 'group' of inventory items that make up one individual item?

When your up for it, definitely send some code my way or use PR, I'm definitely interested!

**Comment by rawcreative** [comment]
Will do..

Kitting/Bundling are similar, but different from Assemblies in general (at least as far as I’m aware). Kitting is basically what you described, where multiple salable products are grouped and sold together as a package of sorts. In the various methods I’ve seen, the end product is not necessarily it’s own product, it’s more of a ‘virtual’ product, and basically decrements the stock of the included products when it’s sold. 

Assemblies on the other hand, while they share the same general concept, are a little more complex, and consist of multiple components. Assemblies are commonly used in manufacturing and probably the most common implementation is a Bill of Materials. So you have multiple raw materials/goods/parts, which make up the end product. So take a table for instance, the finished assembly is that actual table, but it’s made up of individual parts, i.e. 4 legs, a top,  etc. I would say the big difference between kits and assemblies are that assemblies could potentially be multiple levels deep. For instance, in our table example, maybe the table top is the leaf style, which has it’s own parts like hinges/slides/etc and is it’s own assembly. With assemblies, stock moves from the raw materials into the finished assembly when that assembly is created. 

Now I’m sure there’s lots of different ways of handling all of this, and whether the way I’m doing now is the best way I have no idea. But in general the only difference from the base package is that I’ve added an InventoryAssembly class as well as an Inventory Assemblies table. The new table has a product_id, part_id, depth, and quantity, with the product_id and part_id fields both as foreign keys back to the id column on the Inventories table.

**Comment by stevebauman** [comment]
That sounds great, assemblies could definitely be approached by using a nested set table (provided by the package `etrepat/baum` included in the inventory dependencies). However it definitely seems quite complex, and I need to research it more for the best approach. If you've tackled this and your method works, I'd definitely like to implement it in this system. My main goal with this would be ease of use for developers.

I'll take a look around the net and see if I can find any implementations

**Comment by rawcreative** [comment]
I Initially looked at handling the assemblies via nested sets as well but it becomes troublesome with that method when you have an assembly that contains multiples of the same part. Using a closure table just simplified everything. Here's how my assemblies table is structured and an example of what the data looks like.

product_id | part_id  | depth | quantity
-----------|----------|-------|----------
 1  |  1 | 0 | 0 
 1  |  3 | 1 | 2 
 1  |  4 | 1 | 1 
 1  |  5 | 1 | 1
 2  |  2 | 0 | 0 
 2  |  5 | 1 | 2

**Comment by stevebauman** [comment]
Oh ok I understand. Thanks for the table demonstration, definitely helps me wrap my head around it. Are you using another package for managing this closure table? And if so, do they provide a trait based implementation? I just prefer the flexibility of traits over extending so every model can have one base model. 

Saying that however, I'd like to try and see if there's a trait based implementation of baum as well.

**Comment by rawcreative** [comment]
Not currently, I’m handling it manually right now. The only package I know of that handles closure tables is https://github.com/franzose/ClosureTable <https://github.com/franzose/ClosureTable>.  I was going to use that originally but with the way it’s built, there isn’t a way to re-use items in multiple assemblies or have more than one item per assembly. I’ll extract out what logic I have written so far in my app to a couple traits on my fork so you can take a look. There’s still quite a few helper methods I plan on writing, I just haven’t gotten that far yet.

**Comment by stevebauman** [comment]
I see... Should this type of database table be extracted into its own package or is it too unique of an issue to do that? 

I'll wait for your code before I start working on it since you're already on your way to tackling this.

**Comment by stevebauman** [comment]
Also would you be able to explain why [franzose/ClosureTable](https://github.com/franzose/ClosureTable) wouldn't work for this use case? The [migration stubs](https://github.com/franzose/ClosureTable/blob/master/src/Franzose/ClosureTable/Generators/stubs/migrations/closuretable.php) seem like they have the exact same table structure you've shown here?

**Comment by rawcreative** [comment]
Because with that package an item can only have 1 parent. If you try to add the same item as a child of another parent, it removes it from the first. So in this case, you would only be able to use a part in a single assembly, and it could not be re-used.

**Comment by stevebauman** [comment]
Ahh I see, thanks for clearing that up, appreciate it.

**Comment by rawcreative** [comment]
To be fair, my method at the present time isn't really a true closure table that tracks all items, it’s only tracking the assemblies.

**Comment by rawcreative** [comment]
Forgot to post that I pushed a partially-baked version of the assembly functionality here: https://github.com/rawcreative/inventory/tree/assemblies

It's mainly just a starting point, as I'm currently working on other areas of my app right now (purchase orders and receiving). Once I circle back to refining the assemblies piece I'll add more functionality. I added a couple tests for creating an assembly and adding items so you can see how it's currently set up.

**Comment by stevebauman** [comment]
This is awesome, great work! I'm working on the caching issue at the moment which should be fixed shortly, but once that's done I'm going to pull these into my local copy and start playing around with assemblies. Thanks!

**Comment by stevebauman** [comment]
Assemblies have been released. Going to close this for the time being since kits are going to be implemented soon as well.
