### ISSUE TITLE
Issue in migrate

### ISSUE THREAD

**Issue by devmahmed** [stevebauman/inventory#61]
I am ruining this command (php artisan migrate) and its showing error please see screenshot what can i do now? 

![migrate](https://cloud.githubusercontent.com/assets/25400334/23542504/5a374928-000f-11e7-9206-846d674b86bc.jpg)

**Comment by stevebauman** [comment]
Hi @devmahmed,

Looks like you modified the migration, there is no table named `stock`:

https://github.com/stevebauman/inventory/blob/v1.7/src/migrations/2014_07_31_123213_create_inventory_tables.php#L37
