### ISSUE TITLE
Ask: Is it safe to delete inventory_stocks records?

### ISSUE THREAD

**Issue by frdteknikelektro** [stevebauman/inventory#68]
Is it safe to delete inventory_stocks records?

**Comment by frdteknikelektro** [comment]
I think
```use SoftDeletes```
should be added in InventoryStock model

**Comment by kingsloi** [comment]
@frdteknikelektro, I use SoftDeletes on my InventoryStock model no problem. 

`inventory_stock_movements` and `inventory_transaction` both (I believe) have `->onDelete('cascade');` set on their migrations for the stock_id.

**Comment by frdteknikelektro** [comment]
okay, thank you,
for the first time i directly use models with Stevebauman\Inventory\Models namespace.
now I use my own model extending them. and add SoftDeletes.
