### ISSUE TITLE
Inventory Transactions

### ISSUE THREAD

**Issue by stevebauman** [stevebauman/inventory#7]
Thinking of adding an `inventory_transactions` table with it's own `InventoryTransaction` model. This would add the ability of reserving a certain amount of an items stock for a specific transaction. Each transaction would have their own `state` such as:

    //Reserved State
    const STATE_RESERVED_CHECKOUT = 'checkout';
    const STATE_RESERVED_ONHOLD = 'onhold';
    const STATE_RESERVED_BACKORDERED = 'backordered';

    //Cleared State
    const STATE_CLEARED_SOLD = 'sold';
    const STATE_CLEARED_RETURNED = 'returned';
    const STATE_CLEARED_COMPLETED = 'completed';

When a transaction would be created, this would automatically generate a stock movement, so anytime a quantity is reserved for a transaction, it's shown in an item stock movement.

A transaction would be on a 'per stock' basis, so a transaction would be triggered on a specific inventory stock record.

Possibly an API such as:

    $stock = InventoryStock::find(1);

    $stock->reserve(20, InventoryTransaction::STATE_RESERVED_ONHOLD);

An example use case:

An inventory stock is empty, and `reserve()` is called on the stock. The stock isn't available, so the transactions state would be automatically set to `STATE_RESERVED_BACKORDERED`. 

When quantity is added to the stock, you could call:

    $stock->fillBackorders();

    //Or call it on the item to trigger it on all stocks with an optional stock parameter?
    $item->fillBackorders($stock);

This would automatically check for the transactions that were created from first to last, and automatically remove the quantity from the stock if it's available. If there still isn't stock available then the transaction stays open.

**Comment by rawcreative** [comment]
+1  Would be great to have this built in. For the time being I just have a 'claimed' column on my inventory table since I need to track quantity for orders received but not yet fulfilled.

**Comment by stevebauman** [comment]
Glad to know it would be of use!

What are your thoughts on the constants and their names? Would a state named:

    const STATE_RESERVED_CLAIMED = 'claimed';

Be of use to your needs?

Or should these states be customizeable?

**Comment by rawcreative** [comment]
Claimed or Reserved would work fine.. I suppose customizing them  could be useful, but since everything is trait based you could ultimately override that on your model..

**Comment by stevebauman** [comment]
Ok, and that's true, however I wouldn't be able to make them constants as constants can't be implemented in traits. I was going to use an interface so the constants must be implemented inside the model, yet allow the user to keep their own model. I was thinking of making them `public static`, but that means that they can be set anywhere inside the application. Not sure if that'd be a proper implementation of something that's meant to be static or constant...

**Comment by rawcreative** [comment]
btw as I'm dealing with purchase orders and inventory additions right now, it could be extremely useful to have a pending/onorder state as well, which would increment stock levels. Possible values:

`const STATE_ORDERED_PENDING = 'on-order';`
`const STATE_ORDERED_RECEIVED_PARTIAL = 'received-partial';`
`const STATE_ORDERED_RECEIVED = 'received';`

**Comment by stevebauman** [comment]
That's a great idea, i'll add those in as well! I just created a `develop` branch for testing out assemblies and transactions. I'll be pushing your assembly code and some transaction code to it shortly

**Comment by stevebauman** [comment]
I created an interface with the following methods and descriptions to be implemented on the `InventoryTransaction` model. The transactions will be managed independently from the stock since one inventory stock can have many transactions. What are your thoughts?

https://gist.github.com/stevebauman/53178698b1a895be372a

**Comment by rawcreative** [comment]
Looks great to me, only thing I don’t see is how Reserved/Held inventory is cleared/completed..

**Comment by stevebauman** [comment]
Also here is the database schema I was going for:

https://gist.github.com/stevebauman/9dac869eb860b5918804

**Comment by rawcreative** [comment]
I think the having the methods available on the Inventory model might make things simpler but depending on the transaction type is may be better on the stock model.. i.e. in most cases inventory is initially received at a centralized location, and moved to the others, but conversely it's released from many locations. 

For the schema, ideally there should be a way to query the current state of a transaction yes? So for instance if you wanted to run a query for all stock with a state of 'on-order', I don't see a way of doing that with the current schema. Maybe add a open/active/completed column/index on the periods table? That way you could do a join on the periods/transactions for any open/active periods with a state_before of 'on-order'... that make sense?

**Comment by stevebauman** [comment]
Yea, I think some methods will be suitable to be ported to the `Inventory` model, but others will need to stay on a 'by transaction' basis. Will definitely need to experiment with what works.

Also, if you'd like to retrieve all the transactions of a specific state on all stocks, you could use the `whereHas()` method:

    InventoryStock::whereHas('transactions', function($query)
    {
        $query->where('state', InventoryStock::STATE_INVENTORY_ONHOLD);
    })->get();

This could also be wrapped up in a scope or helper function for easier retrieval.

**Comment by rawcreative** [comment]
Ah gotcha, I was thinking that you were making each state change a separate transaction like the stock movements, guess I didn't look closely enough..

**Comment by stevebauman** [comment]
No problem, also your right though it's going to sort of mirror the stock movement functionality. For a transaction, one record will exist for it's lifetime inside of the `inventory_transactions` table, and when a quantity or state has been changed it'll generate a record inside the `inventory_transaction_histories` table (changed the name since 'periods' wasn't exactly the greatest name for explaining what's inside the table, though this still might change). Once a history record has been created, only then will the actual transaction state be changed and quantity be changed.

**Comment by rawcreative** [comment]
Sounds good to me, if you want any help with it just let me know as I'm working on that very thing in my app currently so..

**Comment by stevebauman** [comment]
Ok will do thanks! Working heavily on it now, should most likely be done and tested in a couple days to a week.

**Comment by stevebauman** [comment]
1400 lines later, inventory transactions are done but still need to write tests for every method and possibility. Will take another couple days, however you can try them out using the `dev-develop` branch! Once I have the tests complete and it's good to go for release, assemblies will be next, then kits

**Comment by stevebauman** [comment]
Inventory transactions released
