### ISSUE TITLE
Conflict with existing table while migrating

### ISSUE THREAD

**Issue by bansalvinay** [stevebauman/inventory#70]
Hey Steve,
I liked your project, and was trying to install it with my project. But I had a conflict for a table existing already in table. That table is the permissions table, which is created by another package : spatie/laravel-permission.
How to resolve this problem?

**Comment by kingsloi** [comment]
@bansalvinay, 

if it's easier, you could overwrite/change the tables names for laravel-permission here:

https://github.com/spatie/laravel-permission/blob/master/config/permission.php#L31

**Comment by brunogaspar** [comment]
You sure it's this package fault? As far as i know, this package doesn't have any permissions table.

**Comment by bansalvinay** [comment]
Ohh.. I was trying to migrate, that time I got this error, so I assumed, this. Now I checked, It seems my migrations are corrupted. 
Thanks for help!
