### ISSUE TITLE
Method handle() does not exist

### ISSUE THREAD

**Issue by bansalvinay** [stevebauman/inventory#71]
Hello,
While installation command, there was this error : 
 Method Stevebauman\Inventory\Commands\InstallCommand::handle() does not exist .

What could be the possible reason?

**Comment by kingsloi** [comment]
@bansalvinay,

https://github.com/stevebauman/inventory/blob/v1.7/src/Commands/InstallCommand.php#L31

It's because I believe Laravel 5.5 uses `handle()` and this package uses the older `fire()` method. You'll need to downgrade your Laravel version to 5.3/5.4 to get it to work.

**Comment by bansalvinay** [comment]
Can we expect any upgrade to this package for laravel 5.5? My project is already setup in laravel 5.5, and I don't wish to downgrade it.

**Comment by brunogaspar** [comment]
You can try and fork the repository, fix the issue on your fork and then send a pull request with that fix.

Then in the meantime, you can point Composer to use your forked version so you can continue to work on your project.

**Comment by bansalvinay** [comment]
Ok, I'll try it
