### ISSUE TITLE
Issue while installing

### ISSUE THREAD

**Issue by SwetaKhasale** [stevebauman/inventory#74]
Hey There, I am trying to intsall inventory but when i clone and try to follow steps for laravel 5 but there is no config/app.php in inventory folder...
 i get an erorr i just cannot intall this. please help me.!

**Comment by frdteknikelektro** [comment]
This project shouldn't be cloned.
Install Laravel Project then install this package on that.

**Comment by SwetaKhasale** [comment]
Thank you so much

**Comment by frdteknikelektro** [comment]
You should close this issue then
